name: Build with node, push to docker hub and deploy at VPS

on:
  push:
    branches: [ main ]

jobs:
  build-push-and-deploy:
    name: Build with next, push to docker hub and deploy at VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: sudo docker build -t gabrielwaltmann/working_time_record_api:latest .

      - name: Push docker image
        run: sudo docker push gabrielwaltmann/working_time_record_api

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSWORD }}
          script: |
            cd ~/gabrielwaltmann
            docker-compose pull working-timer-record-backend
            docker compose down working-timer-record-backend
            docker compose up -d --no-deps working-timer-record-backend

