name: Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}  # Use the Node.js version defined in the matrix
          cache: 'pnpm'  # Use pnpm's cache mechanism

      # Step 3: Install pnpm
      - name: Install pnpm
        run: |
          corepack enable  # Enable Corepack (comes pre-installed with Node.js >=16.9.0)
          pnpm install --frozen-lockfile  # Install dependencies using pnpm

      # Step 5: Optional: Build the application
      - name: Build application
        run: |
          pnpm build  # Replace with your build script, if applicable
