name: Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}  # Use the Node.js version defined in the matrix
          cache: 'yarn'  # Change to 'npm' if you're using npm

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          yarn install  # Change to 'npm install' if using npm
          
      # Step 5: Optional: Build the application
      - name: Build application
        run: |
          yarn build  # Replace with your build script, if applicable

